/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AudioComponent: typeof import('./src/components/AudioComponent.vue')['default']
    IHeroiconsPause20Solid: typeof import('~icons/heroicons/pause20-solid')['default']
    IMingcutePlayFill: typeof import('~icons/mingcute/play-fill')['default']
    Slider: typeof import('./src/components/Slider.vue')['default']
    WaveForm: typeof import('./src/components/WaveForm.vue')['default']
  }
}
